apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gouser.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "gouser.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "gouser.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "gouser.name" . }}
    spec:
      containers:
        - name: gouser
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DB_USER
              value: {{ .Values.env.DB_USER | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.env.DB_PASSWORD | quote }}
            - name: DB_HOST
              value: {{ .Values.env.DB_HOST | quote }}
            - name: DB_PORT
              value: {{ .Values.env.DB_PORT | quote }}
            - name: DB_NAME
              value: {{ .Values.env.DB_NAME | quote }}
