apiVersion: v1
kind: Service
metadata:
  name: {{ include "gouser.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ include "gouser.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
  type: {{ .Values.service.type }}
